version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

workflows:
  deploy-all-services:
    jobs:
      - deploy-nomad:
          context: flixtube
          filters:
            branches:
              only:
                - master

commands:
  deploy_nomad:
    description: "Deploy or stop a service on the production Nomad cluster"
    parameters:
      service:
        type: string
      version:
        type: string
      action:  # New parameter to choose between 'deploy' or 'stop'
        type: enum
        enum: ["deploy", "stop"]
        default: "deploy"
    steps:
      - run:
          name: "<< parameters.action | capitalize >> << parameters.service >> (<< parameters.version >>) on the production Nomad cluster"
          working_directory: system/terraform
          command: PATH=.:$PATH; ./deploy_nomad.sh << parameters.service >> << parameters.version >> << parameters.action >>
