version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

parameters:
  service:
    type: string
    default: "default-service"
  version:
    type: string
    default: "1.0.0"
  action:
    type: enum
    enum: ["deploy", "stop"]
    default: "deploy"

jobs:
  deploy-nomad:
    docker:
      - image: circleci/python:3.8  # Choose an appropriate Docker image
    steps:
      - checkout
      - deploy_nomad:
          service: << pipeline.parameters.service >>
          version: << pipeline.parameters.version >>
          action: << pipeline.parameters.action >>

workflows:
  deploy-all-services:
    jobs:
      - deploy-nomad:
          context: flixtube
          filters:
            branches:
              only:
                - master
